services:

  db:
    image: mariadb:11.3.2
    container_name: motos-db
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE:     motos
      MARIADB_USER:         app_user
      MARIADB_PASSWORD:     password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: motos-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: ["npm", "start"]
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: motos-frontend
    depends_on:
      - backend
    ports:
      - "1234:1234"
    networks:
      - app-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    ports:
      - "9100:9100"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
      - node-exporter
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  grafana-storage:

networks:
  app-net:
    driver: bridge
