version: '3.8'
services:

  db:
    image: mariadb:11.3.2
    container_name: motos-db-dev
    environment:
      MYSQL_USER:      app_user
      MYSQL_PASSWORD:  password
      MYSQL_DATABASE:  motos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motos-backend-dev
    depends_on:
      - db             
    ports:
      - "8080:8080"
