name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: motos
        ports:
          - 3306:3306
        options: >-
          --health-cmd "echo OK"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=1

    steps:
      - name: ↓ Descargar código
        uses: actions/checkout@v3

      - name:  Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name:  Instalar dependencias
        run: npm ci

      - name:  Esperar a MariaDB
        run: npx wait-on tcp:3306

      - name:  Instalar cliente MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name:  Inicializar base de datos
        run: |
          mysql \
            -h 127.0.0.1 \
            -P 3306 \
            -u root \
            -ppassword \
            motos < db/script.sql

      - name:  Ejecutar tests
        run: npm test

      - name:  Construir imagen backend
        run: |
          docker build \
            -t motos-backend:${{ github.sha }} \
            -f backend/Dockerfile \
            .

      - name:  Construir imagen frontend
        run: |
          docker build \
            -t motos-frontend:${{ github.sha }} \
            -f frontend/Dockerfile \
            .
