name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11.3.2
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_DATABASE: motos
          MARIADB_USER: app_user
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        # eliminamos healthcheck para que no falle por "unhealthy"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Run unit tests
        working-directory: Actividad-de-aprendizaje/backend
        run: |
          npm install
          npm run unit-test

      - name: Set DB host to localhost for CI
        working-directory: Actividad-de-aprendizaje/backend
        run: |
          sed -i 's/host: .*/host: localhost/' src/config/config.prod.yaml
          cp src/config/config.prod.yaml src/config/config.local.yaml

      - name: Run integration tests
        working-directory: Actividad-de-aprendizaje/backend
        run: npm run integration-test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: Actividad-de-aprendizaje/backend
          file: Actividad-de-aprendizaje/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/motos-backend:latest
            ghcr.io/${{ github.repository_owner }}/motos-backend:${{ github.sha }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: Actividad-de-aprendizaje/frontend
          file: Actividad-de-aprendizaje/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/motos-frontend:latest
            ghcr.io/${{ github.repository_owner }}/motos-frontend:${{ github.sha }}
