name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11.3.2
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_DATABASE: motos
          MARIADB_USER: app_user
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        # ← Quitar options: [...] que definía el health-check

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        working-directory: Backend
        run: npm ci

      - name: Wait for MariaDB to be ready
        run: |
          for i in $(seq 1 15); do
            mysql -h 127.0.0.1 -uroot -prootpassword -e "SELECT 1" && break
            echo "MariaDB no está lista, esperando..."
            sleep 5
          done

      - name: Run migrations & seeds
        working-directory: Backend
        run: |
          npx sequelize-cli db:migrate --env test
          npx sequelize-cli db:seed:all    --env test

      - name: Run unit tests
        working-directory: Backend
        run: npm run unit-test

      - name: Run integration tests
        working-directory: Backend
        run: npm run integration-test
